<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OccupationSeeder extends Seeder
{
    public function run()
    {
        DB::table('occupations')->insert([
            [
                'name' => ' ',
            ],
            ['name' => 'panadero'],
            ['name' => 'albañil'],
            ['name' => 'carpintero'],
            ['name' => 'plomero o fontanero'],
            ['name' => 'electricista'],
            ['name' => 'mecánico'],
            ['name' => 'herrero'],
            ['name' => 'artesano'],
            ['name' => 'basurero'],
            ['name' => 'pintor de casas'],
            ['name' => 'cerrajero'],
            ['name' => 'impresor'],
            ['name' => 'zapatero'],
            ['name' => 'barrendero'],
            ['name' => 'basurero'],
            ['name' => 'trabajador, obrero'],
            ['name' => 'arqueólogo'],
            ['name' => 'arquitecto'],
            ['name' => 'astrónomo'],
            ['name' => 'abogado'],
            ['name' => 'banquero'],
            ['name' => 'biólogo'],
            ['name' => 'corredor de bolsa'],
            ['name' => 'químico'],
            ['name' => 'profesor universitario'],
            ['name' => 'programador de computadoras'],
            ['name' => 'consultor'],
            ['name' => 'dentista'],
            ['name' => 'diseñador'],
            ['name' => 'médico'],
            ['name' => 'economista'],
            ['name' => 'ingeniero'],
            ['name' => 'diseñador gráfico'],
            ['name' => 'historiador'],
            ['name' => 'periodista'],
            ['name' => 'juez'],
            ['name' => 'abogado'],
            ['name' => 'matemático'],
            ['name' => 'enfermera'],
            ['name' => 'oftalmólogo'],
            ['name' => 'pediatra'],
            ['name' => 'filósofo'],
            ['name' => 'médico'],
            ['name' => 'físico'],
            ['name' => 'psiquiatra'],
            ['name' => 'psicólogo'],
            ['name' => 'psicoterapeuta'],
            ['name' => 'reportero'],
            ['name' => 'investigador'],
            ['name' => 'científico'],
            ['name' => 'corredor de bolsa'],
            ['name' => 'cirujano'],
            ['name' => 'inspector de impuestos'],
            ['name' => 'maestro'],
            ['name' => 'traductor'],
            ['name' => 'profesor universitario'],
            ['name' => 'veterinario'],
            ['name' => 'veterinario'],
            ['name' => 'escritor'],
            ['name' => 'cajero de banco'],
            ['name' => 'conductor de autobús'],
            ['name' => 'carnicero'],
            ['name' => 'cajero'],
            ['name' => 'detective'],
            ['name' => 'chófer'],
            ['name' => 'empleado'],
            ['name' => 'florista'],
            ['name' => 'jardinero'],
            ['name' => 'joyero'],
            ['name' => 'bibliotecario'],
            ['name' => 'cartero'],
            ['name' => 'lechero'],
            ['name' => 'cartero'],
            ['name' => 'vendedor'],
            ['name' => 'vendedora'],
            ['name' => 'costurera'],
            ['name' => 'sastre'],
            ['name' => 'taxista'],
            ['name' => 'sastre'],
            ['name' => 'camionero'],
            ['name' => 'bombero'],
            ['name' => 'bombero'],
            ['name' => 'salvavidas'],
            ['name' => 'piloto'],
            ['name' => 'oficial de policía'],
            ['name' => 'policía'],
            ['name' => 'policía'],
            ['name' => 'marinero'],
            ['name' => 'guardia de seguridad'],
            ['name' => 'soldado'],
            ['name' => 'botones de hotel'],
            ['name' => 'chef'],
            ['name' => 'azafata'],
            ['name' => 'azafata'],
            ['name' => 'peluquero'],
            ['name' => 'ama de llaves'],
            ['name' => 'guía de turistas'],
            ['name' => 'agente de viajes'],
            ['name' => 'mesero, camarero'],
            ['name' => 'mesera, camarera'],
            ['name' => 'actor'],
            ['name' => 'actriz'],
            ['name' => 'locutor'],
            ['name' => 'artista'],
            ['name' => 'camarógrafo'],
            ['name' => 'compositor'],
            ['name' => 'bailarín'],
            ['name' => 'modelo'],
            ['name' => 'músico'],
            ['name' => 'fotógrafo'],
            ['name' => 'pianista'],
            ['name' => 'poeta'],
            ['name' => 'editor'],
            ['name' => 'escultor'],
            ['name' => 'cantante'],
            ['name' => 'atleta'],
            ['name' => 'entrenador'],
            ['name' => 'ciclista'],
            ['name' => 'futbolista'],
            ['name' => 'deportista'],
            ['name' => 'vaquero'],
            ['name' => 'agricultor'],
            ['name' => 'pescador'],
            ['name' => 'cazador'],
            ['name' => 'pastor'],
            ['name' => 'empresario'],
            ['name' => 'agente de seguros'],
            ['name' => 'gerente'],
            ['name' => 'recepcionista'],
            ['name' => 'secretaria'],
            ['name' => 'telefonista'],
            ['name' => 'astrólogo'],
            ['name' => 'torero'],
            ['name' => 'caricaturista'],
            ['name' => 'adivino'],
            ['name' => 'monja'],
            ['name' => 'político'],
            ['name' => 'presidente'],
            ['name' => 'sacerdote'],
            ['name' => 'aspirante'],
            ['name' => 'carrera'],
            ['name' => 'certificado'],
            ['name' => 'carta de presentación'],
            ['name' => 'diploma'],
            ['name' => 'anuncio de empleo'],
            ['name' => 'solicitud de empleo'],
            ['name' => 'entrevista de trabajo'],
            ['name' => 'salario'],
            ['name' => 'habilidades'],
            ['name' => 'habilidades sociales'],
            ['name' => 'vacante'],
            ['name' => 'experiencia laboral'],
        ]);
    }
}
