<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VitalSignSeeder extends Seeder
{
    public function run()
    {
        DB::table('vital_signs')->insert([
            [
                'id' => 1,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 2,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 3,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 4,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 5,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 6,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 7,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 8,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 9,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],
            [
                'id' => 10,
                'temperature' => null,
                'weight' => null,
                'breathing_frecuncy' => null,
                'systolic_pressure' => null,
                'diasystolic_pressure' => null,
                'heart_rate' => null,
                'oxygen_saturation' => null,
                'body_mass' => null,
                'body_fat' => null,
                'weight_loss' => null,
                'fat' => null,
                'waist' => null,
                'water' => null,
                'muscle' => null,
                'abdomen' => null,
                'patient_id' => 5,
            ],

        ]);
    }
}
